# Generated by Django 6.0.7 on 2026-07-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=20)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('forma_pagamento', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
