# Generated by Django 6.0.7 on 2026-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naioca', '0003_cliente_alter_itempedido_pedido_alter_pedido_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Pedido recebido'), ('PREPARANDO', 'Preparando'), ('ENTREGA', 'Saiu para entrega'), ('FINALIZADO', 'Entregue')], default='RECEBIDO', max_length=20),
        ),
    ]
